### ISSUE TITLE
Smithing table recipes broken after updating from 3.16.0.0 to 3.16.1.0

### ISSUE THREAD

**Issue by Xiao-MoMi** [WolfyScript/CustomCrafting#60]
### What happened?

First Image is 3.16.0.0

![WAV8G_ 4Q3HE67K3BD{}~EM](https://user-images.githubusercontent.com/70987828/151711385-9e068d84-12a1-4c83-a0b9-32076e01f3f4.png)

Second Image is 3.16.1.0

![KZ~LY2Q9HLZVWN7Y_FDOQKS](https://user-images.githubusercontent.com/70987828/151711413-d5ee9b2f-603e-4e8a-8992-4014d1ecf902.png)

### How can the bug be reproduced?

{
  "group" : "",
  "hidden" : false,
  "priority" : "NORMAL",
  "exactItemMeta" : true,
  "conditions" : {
    "values" : [ ]
  },
  "preserve_enchants" : true,
  "onlyChangeMaterial" : true,
  "result" : {
    "items" : [ {
      "custom_amount" : 1,
      "mmoitems" : {
        "type" : "ARMOR",
        "name" : "龙鳞头盔"
      }
    } ],
    "tags" : [ ],
    "extensions" : [ ]
  },
  "base" : {
    "items" : [ {
      "custom_amount" : 1,
      "mmoitems" : {
        "type" : "ARMOR",
        "name" : "下界合金头盔"
      }
    }, {
      "custom_amount" : 1,
      "mmoitems" : {
        "type" : "ARMOR",
        "name" : "镶金下界合金头盔"
      }
    } ],
    "tags" : [ ],
    "replaceWithRemains" : true,
    "allowEmpty" : false
  },
  "addition" : {
    "items" : [ {
      "custom_amount" : 1,
      "itemsadder" : "xiaomomi:dragon_scale"
    } ],
    "tags" : [ ],
    "replaceWithRemains" : true,
    "allowEmpty" : false
  }
}

### Expected Behaviour?

1

### Plugin version

3.16.1.0 

### Server software

purpur 1.17.1

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Could you try to toggle the `onlyChangeMaterial` option? 
That option was not working in 3.16.0.0 and was fixed in 3.16.1.0, which might have caused this.

**Comment by Xiao-MoMi** [comment]
I know "onlyChangeMaterial" can't be saved in json when the version is 3.16.0.0 and I find this in your source code. So I manually added "onlyChangeMaterial: true" and it works quite well in 3.16.0.0. But this recipe is broken in 3.16.1.0 and I tried a lot but the recipe is still broken.

**Comment by WolfyScript** [comment]
The loading of that value was also broken, so the feature didn't work.
Can you try that recipe it with `onlyChangeMaterial` set to `false`?

**Comment by Xiao-MoMi** [comment]
Wait a min. I'm testing

**Comment by Xiao-MoMi** [comment]
"onlyChangeMaterial set to false" works
Thanks a lot
